pipeline {
    agent {
        docker {
            image 'maven:3.8.3-openjdk-8' // Maven with JDK 8 Docker image
            args '-v $HOME/.m2:/root/.m2' // Mount Maven local repository
        }
    }
    environment {
        MAVEN_HOME = '/usr/share/maven'
        PATH = "$MAVEN_HOME/bin:$PATH"
    }
    stages {
        stage('Build') {
            steps {
                // Checkout the source code
                // checkout scm
                
                // Build the Maven project
                sh 'mvn clean package'
            }
        }
        stage('Run') {
            steps {
                // Run the Java application
                sh 'java -cp target/hello-world-java-1.0-SNAPSHOT.jar com.example.App'
            }
        }
    }
    post {
        success {
            echo 'Pipeline successfully executed!'
        }
       // always {
            // Clean up steps (if needed)
        //}
    }
}
